In [39]:
# Core libraries
import numpy as np
import pandas as pd
import matplotlib.pylab as plt
import matplotlib as mpl
import seaborn as sb

# General utils
from tqdm import tqdm
from os import path

# from sklearn import preprocessing, model_selection, feature_selection, metrics, inspection, pipeline
from skimage import io

dataset_dir = '/Users/xies/Library/CloudStorage/OneDrive-Stanford/Skin/Mesa et al/Lineage models/Dataset pickles'

all_df = pd.read_pickle(path.join(dataset_dir,f'all_df.pkl'))
basals = pd.read_pickle(path.join(dataset_dir,f'basals.pkl'))

basals['LineageID_unique','Meta'] = basals['Region'] + '_' + basals['LineageID','Meta'].astype(str)

for_teemu = basals[[('Cell volume','Measurement cell shape'),
        ('Nuclear volume','Measurement nuclear shape'),
        ('Manual cell volume','Meta'),
        ('Complete cycle','Meta'),
        ('Cell cycle phase','Meta'),
        ('LineageID_unique','Meta'),
        ('Will divide','Meta'),
        ('Will differentiate','Meta'),
                    ]].droplevel(axis=1,level=1)
for_teemu
for_teemu['Manual cell volume'] *= (0.25)**2
for_teemu = for_teemu.reset_index()

In [49]:
basals['LineageID_unique','Meta'].unique().shape

(622,)

NameError: name 'divisions' is not defined

In [38]:
for_teemu.to_csv('/Users/xies/Desktop/for_teemu.csv')

In [57]:
basals.groupby(('Num daughter differentiated','Meta')).count()

,Nuclear volume,Nuclear solidity,Nuclear height,Cell volume,Axial component,Planar component 1,Planar component 2,Axial angle,Planar angle,Z,...,Diff from Mean adjac Axial angle at 1 frame prior,Num neighbor division 1 frame prior,Num neighbor delamination 1 frame prior,At least one daughter differentiated,Both daughters differentiated,Cell cycle duration,G1 duration,SG2 duration,Time to division,LineageID_unique
,Measurement nuclear shape,Measurement nuclear shape,Measurement nuclear shape,Measurement cell shape,Measurement cell shape,Measurement cell shape,Measurement cell shape,Measurement cell shape,Measurement cell shape,Measurement cell position,...,Measurement cell shape adjac diff,Measurement topology,Measurement topology,Meta,Meta,Measurement time,Measurement time,Measurement time,Measurement time,Meta
"(Num daughter differentiated, Meta)",,,,,,,,,,,,,,,,,,,,,
0.0,310,310,310,310,310,310,310,310,310,310,...,249,249,249,310,310,69,258,47,310,310
1.0,513,513,513,513,513,513,513,513,513,513,...,390,390,390,513,513,73,395,71,513,513
2.0,371,371,371,371,371,371,371,371,371,371,...,314,314,314,371,371,192,258,107,371,371

In [60]:
basals.groupby(('Num daughter differentiated','Meta')).count()/len(basals.dropna(subset=[('Num daughter differentiated','Meta')]))

,Nuclear volume,Nuclear solidity,Nuclear height,Cell volume,Axial component,Planar component 1,Planar component 2,Axial angle,Planar angle,Z,...,Diff from Mean adjac Axial angle at 1 frame prior,Num neighbor division 1 frame prior,Num neighbor delamination 1 frame prior,At least one daughter differentiated,Both daughters differentiated,Cell cycle duration,G1 duration,SG2 duration,Time to division,LineageID_unique
,Measurement nuclear shape,Measurement nuclear shape,Measurement nuclear shape,Measurement cell shape,Measurement cell shape,Measurement cell shape,Measurement cell shape,Measurement cell shape,Measurement cell shape,Measurement cell position,...,Measurement cell shape adjac diff,Measurement topology,Measurement topology,Meta,Meta,Measurement time,Measurement time,Measurement time,Measurement time,Meta
"(Num daughter differentiated, Meta)",,,,,,,,,,,,,,,,,,,,,
0.0,0.259631,0.259631,0.259631,0.259631,0.259631,0.259631,0.259631,0.259631,0.259631,0.259631,...,0.208543,0.208543,0.208543,0.259631,0.259631,0.057789,0.216080,0.039363,0.259631,0.259631
1.0,0.429648,0.429648,0.429648,0.429648,0.429648,0.429648,0.429648,0.429648,0.429648,0.429648,...,0.326633,0.326633,0.326633,0.429648,0.429648,0.061139,0.330821,0.059464,0.429648,0.429648
2.0,0.310720,0.310720,0.310720,0.310720,0.310720,0.310720,0.310720,0.310720,0.310720,0.310720,...,0.262982,0.262982,0.262982,0.310720,0.310720,0.160804,0.216080,0.089615,0.310720,0.310720